os:
- linux
- osx
env:
  - MODULE="core"
  - MODULE="metrics"
  - MODULE="rules" DEP="core metrics"
  - MODULE="reporters" DEP="core"

language: cpp
sudo: required
dist: trusty
osx_image: xcode7.2
before_install:
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install cmake; fi
script:
  - cd oclint-scripts
  - ./travis $MODULE $DEP
