os:
- linux
- osx
env:
  - BUILD="test" MODULE="core"
  - BUILD="test" MODULE="metrics"
  - BUILD="test" MODULE="rules" DEP="core metrics"
  - BUILD="test" MODULE="reporters" DEP="core"
  - BUILD="test" MODULE="driver" DEP="core"
  - BUILD="build"

language: cpp
sudo: required
dist: trusty
osx_image: xcode8
before_install:
- if [ $TRAVIS_OS_NAME == osx ]; then
    brew update;
    brew install cmake;
    brew install python;
  fi
- sudo pip install cpp-coveralls

script:
  - cd oclint-scripts
  - ./travis $BUILD $MODULE $DEP
  - cd ..

after_success:
  - if [ $BUILD == test ]; then
      coveralls --gcov $PWD/build/llvm-install/bin/llvm-cov --gcov-options gcov --include oclint-${MODULE}/ --exclude oclint-${MODULE}/test;
    fi

addons:
  artifacts:
    paths:
      - $(ls build/oclint-*.tar.gz)
