os:
- linux
- osx
language: cpp
sudo: required
dist: trusty
osx_image: xcode7.2
before_install:
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install cmake; fi
script:
  - cd oclint-scripts
  - ./travis
